replicaCount: 1

image:
  repository: pratikverman/go-web-page
  pullPolicy: IfNotPresent
  tag: "31874960535"


ingress:
  enabled: false
  className: ""
  annotation: {}
  hosts:
    - host: 
      paths:
        - path: /
          pathType: 
